### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by OleTulling** [PushpenderIndia/crypter#13]
When running the crypted Python on Windows with Python 3.10.4 I get an error:

PS C:\temp> python3 .\yara64.exe
[*] Checking VM
[+] VM Not Detected : )
Password : 1234Traceback (most recent call last):
  File "C:\temp\test.exe", line 52, in <module>
    exec(executable)
  File "<string>", line 1, in <module>
ValueError: source code string cannot contain null bytes

Looking at the code I can not see how the last exec() could work with a Base64 of a PEEXE file.

**Comment by PushpenderIndia** [comment]
This crypter is only for python source code, it will not work for exe

**Comment by OleTulling** [comment]
Ahh, I think you have to state that a bit clearer to the guy that did 125 submissions to Virustotal with PEEXE files ;)
